apiVersion: v1
kind: Template
metadata:
  name: apicurio
  annotations:
    description: "Apicurio"
    iconClass: "icon-load-balancer"
    tags: "api,apicurio,3scale"
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${APICURIO_NAME}"
  spec:
    replicas: 1
    selector:
      deploymentconfig: "${APICURIO_NAME}"
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: "${APICURIO_NAME}"
      spec:
        containers:
        - env:
          image: "${IMAGE_NAME}"
          imagePullPolicy: Always
          name: "${APICURIO_NAME}"
          ports:
          - name: jolokia
            containerPort: 8778
            protocol: TCP
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: https
            containerPort: 8443
            protocol: TCP
          - name: ping
            containerPort: 8888
            protocol: TCP
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    name: "${APICURIO_NAME}"
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deploymentconfig: "${APICURIO_NAME}"

parameters:
- description: "Docker image to use."
  value: 'docker.io/apicurio/apicurio-studio'
  name: IMAGE_NAME
- description: "Name for APICURIO pod"
  value: apicurio
  name: APICURIO_NAME
  required: true

