apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-redis-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /exports/pvs/system-storage/backend-redis
  persistentVolumeReclaimPolicy: Recycle

