apiVersion: v1
kind: PersistentVolume
metadata:
  name: 3scale-storage-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /exports/pvs/system-storage
  persistentVolumeReclaimPolicy: Recycle
