apiVersion: v1
kind: PersistentVolume
metadata:
  name: system-redis-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /exports/pvs/system-storage
  persistentVolumeReclaimPolicy: Recycle

